[build]
  command = "bash install-bin-unix.sh && export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH && pdflatex -interaction=nonstopmode -halt-on-error -output-directory=./output resume.tex"
  publish = "./output/*.pdf"
